// <auto-generated />
using JWTAndApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JWTAndApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250504101214_add_books_seed_data")]
    partial class add_books_seed_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JWTAndApi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "J.R.R. Tolkien",
                            Description = "Orta Dünya'da geçen epik bir macera.",
                            Title = "Yüzüklerin Efendisi"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "J.K. Rowling",
                            Description = "Bir büyücünün büyü dünyasındaki ilk yılı.",
                            Title = "Harry Potter ve Felsefe Taşı"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Fyodor Dostoyevski",
                            Description = "Bir adamın suçluluk psikolojisiyle yüzleşmesi.",
                            Title = "Suç ve Ceza"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "George Orwell",
                            Description = "Baskıcı bir rejimde bireysel özgürlük mücadelesi.",
                            Title = "1984"
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "George Orwell",
                            Description = "Siyasi alegoriyle yazılmış kısa bir roman.",
                            Title = "Hayvan Çiftliği"
                        },
                        new
                        {
                            Id = 6,
                            AuthorName = "Victor Hugo",
                            Description = "Toplumsal adaletin ve kefaretin öyküsü.",
                            Title = "Sefiller"
                        },
                        new
                        {
                            Id = 7,
                            AuthorName = "Fyodor Dostoyevski",
                            Description = "Aile bağları ve felsefi sorgulamalar.",
                            Title = "Karamazov Kardeşler"
                        },
                        new
                        {
                            Id = 8,
                            AuthorName = "Paulo Coelho",
                            Description = "Bir gencin kişisel menkıbesini arayışı.",
                            Title = "Simyacı"
                        },
                        new
                        {
                            Id = 9,
                            AuthorName = "Khaled Hosseini",
                            Description = "İhanet ve bağışlamanın etkileyici hikayesi.",
                            Title = "Uçurtma Avcısı"
                        },
                        new
                        {
                            Id = 10,
                            AuthorName = "Harper Lee",
                            Description = "Irkçılıkla mücadele eden bir avukatın öyküsü.",
                            Title = "Bülbülü Öldürmek"
                        },
                        new
                        {
                            Id = 11,
                            AuthorName = "José Saramago",
                            Description = "Toplumun çöküşüne dair distopik bir roman.",
                            Title = "Körlük"
                        },
                        new
                        {
                            Id = 12,
                            AuthorName = "Aldous Huxley",
                            Description = "Gelecekteki teknoloji kontrolü üzerine.",
                            Title = "Cesur Yeni Dünya"
                        },
                        new
                        {
                            Id = 13,
                            AuthorName = "Jack London",
                            Description = "Bir kurdun hayatta kalma mücadelesi.",
                            Title = "Beyaz Diş"
                        },
                        new
                        {
                            Id = 14,
                            AuthorName = "Honoré de Balzac",
                            Description = "Aşk ve fedakârlığın klasik öyküsü.",
                            Title = "Vadideki Zambak"
                        },
                        new
                        {
                            Id = 15,
                            AuthorName = "Jack London",
                            Description = "Bir yazarın yükseliş ve düşüş hikayesi.",
                            Title = "Martin Eden"
                        },
                        new
                        {
                            Id = 16,
                            AuthorName = "Franz Kafka",
                            Description = "Bir adamın anlam veremediği bir suçlamayla mücadelesi.",
                            Title = "Dava"
                        },
                        new
                        {
                            Id = 17,
                            AuthorName = "Stefan Zweig",
                            Description = "Bir satranç dahisinin psikolojik portresi.",
                            Title = "Satranç"
                        },
                        new
                        {
                            Id = 18,
                            AuthorName = "Lev Tolstoy",
                            Description = "İnsani değerler üzerine kısa hikayeler.",
                            Title = "İnsan Neyle Yaşar?"
                        },
                        new
                        {
                            Id = 19,
                            AuthorName = "Lev Tolstoy",
                            Description = "Toplumsal normlar ve kişisel trajedi.",
                            Title = "Anna Karenina"
                        },
                        new
                        {
                            Id = 20,
                            AuthorName = "Montaigne",
                            Description = "Felsefi ve kişisel düşünceler koleksiyonu.",
                            Title = "Denemeler"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
